### ISSUE TITLE
PatternAttribution for iNNvestigate 2.0 version

### ISSUE THREAD

**Issue by moritzaugustin** [albermax/innvestigate#282]
The great method "PatternAttribution" was available in the previous iNNvestigate version (for tensorflow 1) and is not available anymore for the current version for tensorflow 2.

I wonder whether it is planned to implement the method again and if so when it will be available? :-) 

In the `README.md` it is stated: _pattern.net: [PatternNet](https://arxiv.org/abs/1705.05598) estimates the input signal of the output neuron. (Note:_ ***not available in iNNvestigate 2.0***_)_

**Comment by adrhill** [comment]
Hi Moritz,

I currently don't have the bandwidth to implement "new" features, but I'd welcome contributions.
To check the correctness of a new implementation, data for reference tests can be generated via https://github.com/adrhill/test-data-innvestigate.

I'll leave this issue open as a feature request.

**Note:** For users that are ok with using TensorFlow 1, PatternNet is still available by installing iNNvestigate `1.0.8.`

**Comment by mg97tud** [comment]
I am using tensorflow-directml 1.15 (to use my AMD GPU) and I can use iNNvestigate 2.0 without problems. But when I want to use iNNvestigate 1.0.8.3. I get the Error "module 'tensorflow._api.v1.compat.v2' has no attribute '__internal__'". Is this, because 
iNNvestigate 1.0.8.3 was written and tested for tensorflow 1.12? I sadly cant downgrade from 1.15.

**Comment by adrhill** [comment]
Yes exactly, iNNvestigate 2.0 is a breaking release that switched from TF1 to TF2, dropping TF1 compatibility. 
I'm not familiar with tensorflow-directml, but it would have to be compatible with TF1 for `iNNvestigate 1.0.8` to work.

**Comment by mg97tud** [comment]
Thats what bugging me. Tensorflow 1.15 is the latest Tensorflow 1 Version, right? tensorflow-directml is build on TF 1.15.
I can use innvestigate 2.0 with my 1.15 Tensorflow, but not innvestigate 1.0.8

**Comment by adrhill** [comment]
In case it helps: previous releases of iNNvestigate used Keras `2.2.4` and TensorFlow `1.12`:
https://github.com/albermax/innvestigate/blob/e76ec2d85a6d59d56b6bbb6dbbf1efee6cea6166/README.md?plain=1#L38
https://github.com/albermax/innvestigate/blob/e76ec2d85a6d59d56b6bbb6dbbf1efee6cea6166/setup.py#L11

We then jumped all TensorFlow versions between `1.12` and `^2.6` for iNNvestigate 2.0.
