### ISSUE TITLE
[BUG] 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by dokato** [albermax/innvestigate#262]
### Describe the bug
When calling `analyze` I get:

```
AttributeError:  module 'tensorflow' has no attribute 'get_default_graph'
```

### Steps to reproduce the bug
Ideally include a minimal code example in Python that reproduces the bug:

```python
analyzer = innvestigate.create_analyzer("deep_taylor", model)
a = analyzer.analyze(image)
```

### Expected behavior
It returns analysis.

### Platform information
 - OS:Ubuntu 20.04
 - Python version:  3.9
 - TensorFlow version: 2.5.0 Hence probably related to #214

**Comment by adrhill** [comment]
Hi dokato,

as you have noticed, iNNvestigate's releases currently only support TF1. 
We're working on TF2.0 support. In the meanwhile you can use the [updates_towards_tf2.0 branch](https://github.com/albermax/innvestigate/tree/updates_towards_tf2.0).
