### ISSUE TITLE
PatternNet fails with Keras 2.1.6

### ISSUE THREAD

**Issue by postskript** [albermax/innvestigate#68]
I have the newest Keras 2.1.6 and all_methods.py crashes for PatternNet (`TypeError: softmax() got an unexpected keyword argument 'axis'` etc.). However, it works with Keras 2.1.5.

Tensorflow was on version 1.4.0.

We should probably explicitly ask for these specific versions, at least for the prerelease.
